### ISSUE TITLE
Improve non-free option

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#15]
As mentioned on the mailing list recently (in this thread: https://lists.alioth.debian.org/pipermail/freedombox-discuss/2015-April/006752.html), non-free is currently enabled for some platforms that don't need it.

IMHO we should just disable non-free by default for all platforms. We can let the user set the ENABLE_NONFREE environment variable on the command line if they wish. Also I think it would be nice to add a "non-free" label to the image filename if it includes non-free parts.

**Comment by SunilMohanAdapa** [comment]
When the non-free configuration option was introduced, the ENABLE_NONFREE flags set on most configurations just so that we don't agressively break things.  The idea is that when we confirm that non-free components are not required, we would remove from each.  We should do that now.

I would indeed be nice to set a non-free label in the filename.  I think only one of our current images requires it, IIRC.  Either raspberrypi or the dreamplug.

**Comment by jvalleroy** [comment]
I think this is fixed now with #22 and #23. Please reopen if any additional changes are needed.
