### ISSUE TITLE
Use Debian package for vmdebootstrap

### ISSUE THREAD

**Issue by infertux** [freedombox/freedom-maker#47]
I wonder if we still need [bin/fetch-new-vmdebootstrap](https://github.com/freedombox/freedom-maker/blob/master/bin/fetch-new-vmdebootstrap) to fetch the Git version of vmdebootstrap now that it has been [packaged in Debian `jessie` and `wheezy-backports`](https://packages.debian.org/search?keywords=vmdebootstrap&searchon=names&suite=all&section=all).

I tried to run `make a20-olinuxino-lime2` and it works fine with `jessie`'s package.

I reckon it's cleaner to use distro packages when available unless we want to support building for older Debian releases? Thoughts?

**Comment by infertux** [comment]
We might need to upstream [this patch](https://github.com/freedombox/freedom-maker/blob/master/vendor-patches/vmdebootstrap/03-roottype-btrfs-bts-741223.patch) first although I'm not sure where it is used.

**Comment by SunilMohanAdapa** [comment]
The vmdebootstrap bug to upstream the changes is here:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741223

I believe, the patch can and must be simplified.

**Current state**: The current patch creates a subvol called "@" and then makes a lot of code changes to various activities to make sure that all the activities happen on that subvol.  The main brtfs volume is mounted and then root directory path (the subvolume to work on) argument is passed to all the necessary functions.  This technique is based on conventions specified in https://help.ubuntu.com/community/btrfs.  On this page, the only reason specified for not using default subvolume feature of btrfs is that it does not work with rootfsflags recommended in the page.  I find that this convention makes it easy to examine subvolumes and organize them but makes it hard to actually use a subvolume.  Typical process of reverting to a snapshot (which is a subvolume) involves switching the default subvolume and rebooting.  However, in this convention, switching to a subvolume involves changing boot arguments and modifying the fstab.  From a reliability point of view, this is troubling because we have to reliably update the uboot environment, grub configuration and fstab.

**Proposal**:  We should use the default volume feature of the btrfs filesytem and we should not pass "subvol=@" etc. in fstab and kernel boot arguments.  In fact we should not even create a default subvolume called "@".  Then the patch will become very simple.  No need to create subvolume, no need to pass rootfsdir to all methods, no need for extra /btrfs directory, no need to have special grub arguments and no need to have special fstab options.  The patch should simply create filesystem with type 'btrfs' then treat it like any other filesystem by mounting, debootstrapping, running grub-install etc.  This mostly means that the patch is not necessary.  We just need to create some upstream test cases to make sure btrfs is working fine. 

Snapshotting tools will then deal with complexity of snapshots/subvolumes. A good example is how Snapper (snapper.io) works.  It creates snapshots underneath /.snapshots.  When someone reverts to a snapshot, it will set the default subvolume of the btrfs filesystem and recommend a reboot.  All of this can be done without the "@" subvolume.  I will post a separate proposal for snapshotting in FreedomBox in more detail based on this plan.

Looping in @petterreinholdtsen, the original author of the patch for comments.

**Comment by petterreinholdtsen** [comment]
I do no longer remember the details, but the goal when went with this
approach to picking the btrfs root was to be able to snapshot the
current system (assuing / contain /etc/, /var/, /usr/ and everything
else needed to run the system), upgrade it, boot into the new system and
conclude that the upgraded system is broken, boot it again and change
the boot parameter to get back to the old system by changing subvol=@ to
subvol=<oldsnapshot>.

Will this use case still work with your new approach, is is the only way
to change the root to have a working system to boot into to change the
default subvolume?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SunilMohanAdapa** [comment]
There is more discussion going on in the upstream BTS bug.  Sorry to
have started the same discussion in two places.

-- 
Sunil

**Comment by infertux** [comment]
Thanks a lot guys for the details. I'm gonna close this issue to avoid duplication. Please refer to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741223

**Comment by infertux** [comment]
See also #45.
